/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_srt_iis_spark_CarAnalysis */

#ifndef _Included_com_srt_iis_spark_CarAnalysis
#define _Included_com_srt_iis_spark_CarAnalysis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_srt_iis_spark_CarAnalysis
 * Method:    getCar
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_srt_iis_spark_CarAnalysis_getCar
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
